//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMAT
    {
        public int TE_id { get; set; }
        public int KA_id { get; set; }
        public string TE_nazwa { get; set; }
    }
}
