//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UZYTKOWNIK
    {
        public int UZ_id { get; set; }
        public string UZ_login { get; set; }
        public string UZ_haslo { get; set; }
        public string UZ_pseudonim { get; set; }
        public string UZ_przywileje { get; set; }
        public System.DateTime UZ_data_dolaczenia { get; set; }
        public bool UZ_zablokowany { get; set; }
    }
}
